title = "My New Hugo Site"
baseurl = "https://snf-8325.ok-kno.grnetcloud.net"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
publishDir = "/var/www/html/"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
