title = "ehlo!"
baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
publishDir = "/var/www/html/"
enableEmoji = true

[permalinks]
    posts = "/:year/:month/:title"

[params]
    showReadingTime = true
    showMenuItems = 2

[languages]
    [languages.en.params.logo]
        logoText = "lgian"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
